### ISSUE TITLE
README edit

### ISSUE THREAD

**Issue by BartMassey** [tolga9009/sidewinderd#17]
In the README, probably want to enable `sidewinderd` before starting it, rather than the other way around.

**Comment by tolga9009** [comment]
Hi,

you're correct. Fixed it in commit 2002cdb15d0041ace60bb72d6967eca92ac3f27c. Thank you for reporting!

Cheers,
Tolga

**Comment by BartMassey** [comment]
Thanks huge for sidewinderd! Having big fun with it.

**Comment by z3ntu** [comment]
btw there's also the option to use `systemctl enable --now <something>.service` to start&enable a service in one command ;) (support for that was added in systemd 220, so it should be available in all distros by now)

**Comment by BartMassey** [comment]
Thanks!
