### ISSUE TITLE
Fails to load tinyxml2-4.0.1 (update from 3.0.1)

### ISSUE THREAD

**Issue by Jakeler** [tolga9009/sidewinderd#18]
`/usr/bin/sidewinderd: error while loading shared libraries: libtinyxml2.so.3: cannot open shared object file: No such file or directory`

Obviously there is now `libtinyxml2.so.4`. A simple symlink to the the new file works fine for me, so there should be no real changes necessary. You could try to load the version independent `libtinyxml2.so` instead.

Edit: Okay, i see that you search at build time for the libs and a rebuild solves the issue. But it would be still better if it directly prefers `libtinyxml2.so` (without specific version).

**Comment by tolga9009** [comment]
Hi there,

thanks for reporting! I think this is an issue outside the scope of this project. We're not searching for a specific version of TinyXML2. CMake searches for TinyXML2 on your system and picks up whatever version you've installed and links against it.

I've also successfully built and used sidewinderd with TinyXML2 4.x, without any issues. You probably needed to clean up build directory or rebuild after updating TinyXML2.

I'm not sure, if it's a good idea to link against version neutral `.so`. There might be API changes or other changes, which may need attention when updating to a new major version of a library. Besides, major updates of libraries are rare and I don't think, we have to handle them this way. Instructing users to rebuild should be enough. If there are any incompabilities with new major versions, they will show up during compliation, which is a good thing.

Cheers,
Tolga

**Comment by Jakeler** [comment]
Okay, thanks for your explanation.
Is there somewhere a message that tells the user to rebuild after a library upgrade? Because i was just wondering yesterday why my keyboard is not working properly anymore and after checking the log i thought sidewinderd is incompatible to TinyXML2 4.x... If this is already there it should be more noticeable, or maybe i am just blind ;)
