### ISSUE TITLE
Crash while doing something?

### ISSUE THREAD

**Issue by z3ntu** [tolga9009/sidewinderd#19]
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: Found device: 045e:0768
> Okt 01 18:33:14 g550jk sidewinderd[31327]: terminate called after throwing an instance of 'std::logic_error'
> Okt 01 18:33:14 g550jk sidewinderd[31327]:   what():  basic_string::_M_construct null not valid
> Okt 01 18:33:14 g550jk systemd[1]: sidewinderd.service: Main process exited, code=killed, status=6/ABRT
> Okt 01 18:33:14 g550jk systemd[1]: sidewinderd.service: Unit entered failed state.
> Okt 01 18:33:14 g550jk systemd[1]: sidewinderd.service: Failed with result 'signal'

I have no idea what happened there or what I did there :/

~~And another question: where (which file) does sidewinderd store the macros?~~ **EDIT:** Found it: `~/.local/share/sidewinderd/`, that information should be added to the README though.

**Comment by tolga9009** [comment]
Hi,

thanks for reporting this issue! I will investigate it, but I need to know your system specs. Are you running this on a x86_64 desktop? Or something like a Raspberry Pi (ARM)?

Cheers,
Tolga

**Comment by z3ntu** [comment]
It was on my x86_64 laptop.

**Comment by Jakeler** [comment]
Any progess so far? I have the same issue on ArchLinux x86_64, but it happens very infrequently, a few times in a month, so i am also not sure what exactly causes this.

**Comment by z3ntu** [comment]
My journal of sidewinderd since October (when I first noticed it): http://pastebin.com/XJCEWDEV (search for `throwing an instance of`). The crash happened 16 times since October so it's not that frequent but still too often

**Comment by Jakeler** [comment]
I looked into my journal, it happend first on 16. September and 11 times in the meantime...
You could add `Restart=on-failure` to the systemd service file as temporary solution, i dont even notice it most of the time when it restarts after a crash.

**Comment by tolga9009** [comment]
Sorry, I didn't had time to look further into the code yet. Thanks for the log @z3ntu! Looks like, this is an issue, which happens in long-term use. Perfectly explains, why it's so difficult to reproduce and debug it. Very helpful!

I think I have a good idea on how to fix it and what the problem is, but I can't give you an ETA yet. Very unmotivated and busy at the moment, I'm sorry.

**Comment by tolga9009** [comment]
Heys!

I have good news: just found the issue! The udev functions sometimes return `NULL`, when something went bad or something couldn't be read. And I wrote the code in a way, where this `NULL` would be directly passed to a `std::string()` constructor, leading to a crash.

The solution is to filter out `NULL` returns, before passing them to a `std::string()` constructor. You can expect a patch within the next few hours.

My apologies for letting you guys wait for so long.

Cheers,
Tolga

**Comment by z3ntu** [comment]
I installed the package from the newest revision and will report back in a month or so what happened ;) (maybe you have to remind me to check my logs)

**Comment by tolga9009** [comment]
I've successfully tested this for over a day now with my Logitech G710+ and made sure, nothing else broke. I think it's a good time to release `0.4.1`. I will wait a few weeks and if I don't get any more bug reports regarding this issue, I will close here.

Cheers,
Tolga
