### ISSUE TITLE
Wont play macro

### ISSUE THREAD

**Issue by WantedFreak** [tolga9009/sidewinderd#21]
```Started sidewinderd.
Found device: 045e:0768
Can't open uinput
Keyboard Constructor
getFeatureReport(7) returned: 7 4
getFeatureReport(7) returned: 7 0
getFeatureReport(7) returned: 7 0
getFeatureReport(7) returned: 7 0
getFeatureReport(7) returned: 7 0
getFeatureReport(7) returned: 7 0
getFeatureReport(7) returned: 7 4
getFeatureReport(7) returned: 7 64
Start Macro Recording on /dev/input/event3
getFeatureReport(7) returned: 7 44
Exit Macro Recording
```
Recorded "sudo !!" on S1 and got this output but it wont type that in the console or in any text field.

Im using M$ X4, kernel is x86_64 Linux 4.8.11-1-ARCH and desktop env is XFCE4

**Comment by tolga9009** [comment]
Hi @WantedFreak,

thanks for the bug report. `uinput` is needed to inject key events, which couldn't be opened on your system, according to your log: `Can't open uinput`.

First of all, I'd make sure, that either `/dev/uinput` or `/dev/input/uinput` is existing on your system. If it's not, it might be possible, that it's in another location and we need to make adjustments to search in those locations aswell.

Next, check its permissions and make sure `sidewinderd` has write-access to them. Our current design needs you to run `sidewinderd` daemon process as root, with your desktop user configured in `/etc/sidewinderd.conf`. However, if you're running `sidewinderd` process as non-root user, it's very possible, you don't have enough permissions to open and write to `uinput`.

I assume you're running Arch Linux? In that case, `uinput` kernel support is enabled by default and usually you should be good to go out-of-the-box. I will personally test this on latest kernel aswell and report back.

**Comment by WantedFreak** [comment]
Hi. Yes I installed via AUR, first time using this package. I've tried using systemd and `sudo sidewinderd` . I've set my username in the config and uinput is at `/dev/uinput.` Setting 666 on uinput did not change anything.

**Comment by tolga9009** [comment]
I need to check specific error code on the failed command. I could imagine, that maybe another application is blocking sidewinderd from opening uinput.

Or, something is wrong with the privilege elevation in sidewinderd. So far, we're not checking, whether `seteuid(0)` succeeds or not.

Both things need to be patched in code, then we can revisit this issue and see, where the issue is precisely.

**Comment by WantedFreak** [comment]
This is working now. I just tried and it works perfectly.
