### ISSUE TITLE
Sidewinderd misses recommended --help command line switch

### ISSUE THREAD

**Issue by luziferius** [tolga9009/sidewinderd#24]
Hi,

As the title reads, sidewinderd misses the --help command line switch, which is recommended by GNU:
[https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html)

Greetings,
Thomas

**Comment by luziferius** [comment]
I have added that switch in this branch: [feature/cmd_line_help_switch](/luziferius/sidewinderd/tree/feature/cmd_line_help_switch). But I’m not quite sure about the implementation. It does not simply dump some const char* to std::cout. The code lets you define options in a almost declarative manner and then formats the output when requested.
Declare options [like this](/luziferius/sidewinderd/blob/796e836cf4ea4db3f1534e168b82273a8d7b17b2/src/core/cli_help.cpp#L62-L69) and get neatly aligned output without ever breaking the formatting (as long as there are no multi-byte unicode characters in short/long options…).
The downside is that this code requires C++14 syntax to declare the options array and some of the constexpr magic used.

**Comment by tolga9009** [comment]
Hi there!

Thanks for your efforts! Your implementation definitely makes sense for a more feature-rich CLI program, like e.g. ffmpeg. However, bumping up C++11 requirements to C++14 for showing the help text is indeed a bit overkill.

At least in the current state, I think it makes more sense to go for a simple `std::cout` solution here. I don't have huge plans for CLI, so I don't think it will get hugely more complex in near future.

I will see, if I can reuse some parts. Thank you!

Cheers,
Tolga

**Comment by tolga9009** [comment]
I've pushed out d6d2513dad4a044aaecb297e41bf5e5f04e7bbf1, which addresses this issue. Feel free to make further adjustments, if something stays unclear or is phrased incorrectly. I'm closing this issue now.

Thanks for reporting!

Cheers,
Tolga

**Comment by luziferius** [comment]
I could have done the same thing in C++11, but it won’t look as neat (at least for me my C++14 implementation looks neat^^), because of a different, less readable initializer syntax.
As I stated initially, my solution »might be a bit overkill«. So no problem for not using it.

I annotated some bits in your linked commit diff. I feel like doing a pull request for that small change is a bit much.

Greetings,
Thomas

**Comment by tolga9009** [comment]
Problem with C++14 is, that it's not as wide-spread and well-supported as C++11. For Arch Linux users, this might be not an issue, but there are several Linux distros out there, which have a much longer lifecycle and often ship old software versions. I don't want to exclude users of those distros for features, which can be implemented using C++11.

Cheers,
Tolga
