### ISSUE TITLE
Recording works with plugged-out mouse - playback not

### ISSUE THREAD

**Issue by macmacs** [tolga9009/sidewinderd#3]
Hi there,
great thing, you try to get all the functionalities working!!

After compiling and starting sidewinderd I found out, that recording only works with plugged-out mouse.

But the playback doesn't work neither way.
I checked the xml files and there's content - looks good!

`...`
`<DelayEvent>10</DelayEvent>`
`<KeyBoardEvent Down="0">30</KeyBoardEvent>`
`<DelayEvent>100</DelayEvent>`
`<KeyBoardEvent Down="1">50</KeyBoardEvent>`
`<DelayEvent>10</DelayEvent>`
`...`

I am running Linux Mint 17 (based on Ubuntu 14.04).
Do you need any logfiles?

Would be great if I got these keys to work :+1: 
Regards
Max

**Comment by tolga9009** [comment]
Hi macmacs,

> After compiling and starting sidewinderd I found out, that recording only works with plugged-out mouse.

there is currently a known bug, which seems related to your issue. Problem is, that `DeviceHandler::udev` is broken and is not finding the correct `/dev/inputX` file. It is only confirming, that the `/dev/inputX` is of type `ID_INPUT_KEYBOARD`; nothing else.

This is an issue on systems, where more than 1 keyboard exists, or a USB receiver (like the Logitech ones) is plugged in. I guess your mouse supports macro playing and probably is a USB composite device, which is detected by your OS as 2 devices (1 HID mouse and 1 HID keyboard for macro functionality).

I hadn't considered it as a critical bug, as I completely forgot about those special USB receivers, which are broadly used. I'll focus on this bug and get it fixed next.

> But the playback doesn't work neither way.
> I checked the xml files and there's content - looks good!

Not sure, but there was an issue with creating the uinput device, which is needed for sending keystrokes to the operating system. While I was refactoring the code, there was some odd issue with the `VirtualInput` object. I haven't read more about it yet, but I think it has to do with raw / unique pointers. I will dig into this as soon as possible. In the meantime, I suggest you stick with release 0.1.2, until I have fixed this issue.

Thanks for your feedback!

Cheers,
Tolga

**Comment by tolga9009** [comment]
I have just fixed the recording issue. Please test and report back please. Now hunting down the playback issue ;)!

Cheers,
Tolga

**Comment by tolga9009** [comment]
Okay, latest commit should fix playback issues. I'm waiting for your feedback, so I can close this issue ;)!

Cheers,
Tolga

**Comment by tolga9009** [comment]
It seems to work for a while now. I'm assuming, that this is fixed now. If not, please file a new bug.

Cheers,
Tolga
