### ISSUE TITLE
support for Logitech G815 Keyboard

### ISSUE THREAD

**Issue by cornernote** [tolga9009/sidewinderd#40]
I was using a G105 and sidewinderd has been perfect.  I got a new G815 and plugged it in, half expecting it to work, however it didn't.

I'm not sure where to start.  Any tips would be appreciated.

**Comment by cornernote** [comment]
have made some progress here - https://github.com/cornernote/sidewinderd

the keyboard instructions are very different, so its taking me a bit to fiddle

**Comment by cornernote** [comment]
See PR #41

**Comment by tolga9009** [comment]
Hi!

Thanks for all your efforts! Sorry for not replying late. I'll take further discussion into the PR and close here.

Cheers,
Tolga
