### ISSUE TITLE
sidewinderd[2817]: Error accessing /root/.local/share/sidewinderd.

### ISSUE THREAD

**Issue by mrazster** [tolga9009/sidewinderd#44]
Hi !
I have been using sidewinderd for a while in different distros and it has been working really well and it has been a great tool. So thanks a bunch for creating this.

However I have run in to a problem with my latest install.
I´m on Arch and I have tried both the sidewinderd and sidewinderd-git from tha AUR and I have tried to compile and installing it manually by downloading directly from this repo. But my problem is the same and it persists. After enabling and starting the service nothing happends and it doesn´t start.

When doing `systemctl status sidewinderd.service` in terminal I get this:
```
sidewinderd.service - Support for Microsoft SideWinder X4 / X6 and Logitech G105 / G710+
     Loaded: loaded (/usr/local/lib/systemd/system/sidewinderd.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2020-07-14 21:16:35 CEST; 14s ago
    Process: 2817 ExecStart=/usr/local/bin/sidewinderd (code=exited, status=1/FAILURE)
   Main PID: 2817 (code=exited, status=1/FAILURE)

jul 14 21:16:35 mrazsternator systemd[1]: Started Support for Microsoft SideWinder X4 / X6 and Logitech G105 / G710+.
jul 14 21:16:35 mrazsternator sidewinderd[2817]: Error accessing /root/.local/share/sidewinderd.
jul 14 21:16:35 mrazsternator systemd[1]: sidewinderd.service: Main process exited, code=exited, status=1/FAILURE
jul 14 21:16:35 mrazsternator systemd[1]: sidewinderd.service: Failed with result 'exit-code'.
```

I have looked for /root/.local/share/sidewinderd as mentioned in the errorcode, but it´s simply just not there. Any ideas or mabye point me in a direction as where to look ?

**Comment by tolga9009** [comment]
Hi,

thank you for the bug report!

If not configured after install, sidewinderd falls back to `root` user. If you change the user in `/etc/sidewinderd.conf` it should work. We have hints for this in README, aswell as during your first install using `pacman` (https://aur.archlinux.org/cgit/aur.git/tree/sidewinderd.install?h=sidewinderd). I think updating doesn't trigger the message, only new installs.

Please close the issue, if the above fixed it.

**Comment by mrazster** [comment]
> Hi,
> 
> thank you for the bug report!
> 
> If not configured after install, sidewinderd falls back to `root` user. If you change the user in `/etc/sidewinderd.conf` to your desktop user, it should work. We have hints for this in README, aswell as during your first install using `pacman` (https://aur.archlinux.org/cgit/aur.git/tree/sidewinderd.install?h=sidewinderd). I think updating doesn't trigger the message, only new installs.
> 
> Please close the issue, if the above fixed it.
> 
> Cheers,
> Tolga

Yes that did the trick ! :-) 
Thank you so much for fast reply and good support !
I have never had to do that before on any distro..wich i find weird.
But anyhow...thnx again, much appreciated !
