### ISSUE TITLE
Is there any way to assign media controls to the G keys?

### ISSUE THREAD

**Issue by Nikorasu** [tolga9009/sidewinderd#46]
I was hoping to assign things like Volume up/down/mute to my G keys, but I'm relatively new to Linux, and after searching through documents here, I can't seem to find any way to do it, or if it's even possible..
EDIT:
Thanks for the reply! That worked perfectly! Not sure how I missed those event codes. heh

**Comment by tolga9009** [comment]
Hi,

I'm very sorry for the late answer. There are multiple ways to achieve this. One way to achieve this: edit macro XML files directly. You can find them under ~/.local/share/sidewinderd/profile_X, whereas X is your active profile. E.g. for assigning Play/Pause Media Key to G1 on M1 profile, you need to do the following:
1. Open file `~/.local/share/sidewinderd/profile_1/s1.xml`. If it doesn't exist, create it.
2. Look up your desired keycode under https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h. In our example, it's `KEY_PLAYPAUSE` = `164`.
3. Replace the content of `s1.xml` by the following:
```
<Macro>
    <KeyBoardEvent Down="true">164</KeyBoardEvent>
    <KeyBoardEvent Down="false">164</KeyBoardEvent>
</Macro>
```
4. Now your G1 Key should act like Play/Pause button. You can do this for more buttons.

An alternative to this approach would be assigning more generic keycodes to your G1 - G6 keys (e.g. F13 - F24) or more recent kernels `KEY_MACRO1` and re-assigning keyboard actions via your desktop environment GUI. E.g. GNOME can do it under "Settings -> Keyboard Shortcuts". Your DE needs to support your desired keycodes though and not all of them do.

Hope this helps!

Cheers,
Tolga
