### ISSUE TITLE
sidewinderd needs to be reloaded after boot, if the user folder is encrypted

### ISSUE THREAD

**Issue by tolga9009** [tolga9009/sidewinderd#6]
sidewinderd can't access user folders, if the home folder is encrypted. This is only true, when sidewinderd is running as a non-root user - which is the preferred and recommended method. This can probably be fixed by letting sidewinderd.service wait for the harddrive encryption service to finish by using "After" parameter. Original bug report: http://ubuntuforums.org/showthread.php?t=1543370&page=6&p=13278148#post13278148

Cheers,
Tolga

**Comment by tolga9009** [comment]
Not entirely sure, how this can be fixed. First, I thought about waiting for `home.mount`, but it isn't an option, as some systems don't have a dedicated `home` partition (including me). I will try waiting for `cryptsetup` to complete, maybe it will fix it. But to be honest, I'm a bit clueless on this one.

**Comment by tolga9009** [comment]
I've come up with 2 ideas, how to fix this issue: either, we add the systemd service option `RequiresMountsFor=$HOME`. Or we use autostart from a desktop environment. The first option is definitely more *lightweight*, but I'm not sure, if it will fix this issue in all scenarios. Like when the `/home` directory is mounted as `noauto`.

Option 2 would definitely fix this issue, but there are tons of different DEs out there to take care of.

I'm gonna try out a bit now.

**Comment by ntzrmtthihu777** [comment]
Not sure how this would work when ran as a systemd user service, but perhaps that would outright fix this issue as logging in with an encrypted `$HOME` typically decrypts and mounts it.

**Comment by tolga9009** [comment]
Most probably, yes. But I want to fix this in a portable manner, like in systems without systemd and also on Mac OS X / FreeBSD. This needs to be fixed in code.

2 approaches, I've thought about:
1. possibility to define another directory to use in`/etc/sidewinderd.conf`, which is available without decrypting.
2. Handle read errors in program code. Introduce a new flag e.g. `-e` which is used in conjunction with encrypted systems, so sidewinderd tries to access encrypted folders / files infinitely in intervals. Default behaviour should be: quit sidewinderd and log error.

**Comment by ntzrmtthihu777** [comment]
To be frank I don't see why this needs an OSX port (unless its for the sidewinder stuff) since logitech has an OSX driver for the G### devices

**Comment by tolga9009** [comment]
I'm planning to open up the gates for supporting more vendors / keyboards in the future. I want sidewinderd to become some sort of framework for gaming peripheral drivers.

Yes, SideWinder keyboards don't have Mac OS X support. A broader device / platform support means catching the attention of more developers, resulting in better software.

I'm kinda sick to see people reinventing the wheel everytime a new gaming keyboard gets released. This is why I'm trying to create one driver to rule them all. And this includes Mac OS X support.

Honestly, if Windows wouldn't be that much different, I'd have no shame to port this to Windows and replace the crappy Logitech drivers. It's not like they're doing a good job...

**Comment by ntzrmtthihu777** [comment]
Ah gotcha. In which case, I'd suggest renaming it to something more generic (not to mention M$ might be dicky about the name sidewinder in your software). Yeah, and then the individual projects get abandoned (g15daemon/gnome15) and digging through the code is a bit crazy indeed.

Yeah, if Windows had a sane POSIX based system life would be much easier for everyone, but nope.

**Comment by tolga9009** [comment]
Yeah, I'm gonna think about a good name :)! Eventhough I really like sidewinderd.

**Comment by ntzrmtthihu777** [comment]
I was thinking something remeniscent of shadowrun personally.

**Comment by tolga9009** [comment]
Commit d650064e595563c0e895bbdd2c6983d1c28ee73f partly fixes this issue. It allows the user to define a custom path, independent from user's home directory. Set this, if you want to define a custom directory, which is not guaranteed to be available for the user at boot.

As an alternative, I will add another setting option / commandline flag, which will block the program, until it manages to get access to users `/home` directory. In the future, we will also have `systemd --user` services, which get started, as soon as a user logs in. I think, we will cover most cases with all three options, making commit d650064e595563c0e895bbdd2c6983d1c28ee73f a last way out.

**Comment by tolga9009** [comment]
Commit e8fe20fa24eb01dd853f9b84ae7b9fc14cab2eae fixes this bug. If you want sidewinderd to wait for your encrypted home folder to become available, simply set uncomment and set `encrypted_workdir` to `true` in the configuration file. This will make sidewinderd wait for the `/home/<user>/.local/share` directory.

Default behaviour is: `encrypted_workdir` = `false`, sidewinderd will terminate, if it can't access workdir and log the error.
